version: '3'

services:
  wormhole:
    restart: always
    image: dollarkiller/wormhole:latest
    ports:
      - "8200:8200"
      - "8201:8201"
    tty: true
    volumes:
      - ./proxy.crt:/app/proxy.crt:ro
      - ./proxy.key:/app/proxy.key:ro
    command: /app/wormhole_server_linux_x86 -l 8200 -r 8201 -c /app/proxy.crt -k /app/proxy.key
