version: "3.3"
services:
  wormhole_client:
    image: wormhole_client:0.0.1
    container_name: wormhole_client
    restart: always
    network_mode: "host"
    environment:
      - r=192.227.234.228:8454
      - n=rocky192.168.31.61
    command: /app/wormhole_client -r 192.227.234.228:8454 -n rocky192.168.31.61
    volumes:
      - ./configs/:/app/configs

